---
- name: configure important user consistently
  hosts: test
  gather_facts: yes
  tasks:

    - name: newbie exists with UID 4000
      user:
        name: newbie
        uid: 4000
        state: present