---
- name: Play to setup web server
  hosts: test
  gather_facts: yes
  tasks:

    - name: Install the httpd service
      dnf:
        name: httpd
        state: present


    - name: Enable and restart the http service
      service:
        name: httpd
        enabled: yes
        state: restarted