---
- name: Play to remove the HTTPD packages
  hosts: test
  gather_facts: yes
  tasks:

    - name: Stop the Httpd service
      service:
        name: httpd
        enabled: no
        state: stopped

    - name: Remove the httpd packages
      dnf:
        name: httpd
        state: absent