---
- name: Install Docker CE and other dependencies for docker
  hosts: docker_ubuntu
  gather_facts: no
  tasks:

    - name: Update the current packages
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - curl
          - gnupg-agent
          - ca-certificates
          - software-properties-common
        state: present


    - name: Copy Docker GPG Key to keyring directory
      copy:
        src: ./docker-archive-keyring.gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: '0644'


    - name: Add Docker repository line to sources list
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable'
        create: yes
#        state: present
#      register: docker_list

    - name: Update the current packages
      apt:
        update_cache: yes

    - name: Install Docker engine, engine cli, container io and docker compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present
      notify: Enable and Start the docker daemon service


  handlers:
    - name: Enable and Start the docker daemon service
      service:
        name: docker
        enabled: yes
        state: restarted


    - name: Add "ubuntu" user on docker group
      user:
        name: ubuntu
        groups: docker
        append: yes