---
- name: Setup password less authentication
  hosts: node_2
  gather_facts: no
  tasks:

    - name: Remove authentication by password
      lineinfile:
        path: /etc/ssh/sshd_config
        search_string: 'PasswordAuthentication yes'
        line: PasswordAuthentication no
        owner: root
        group: root
        mode: '0644'