---
- name: Create an user for with secret variables
  hosts: test
  gather_facts: yes
  vars_files:
    - secret.yaml
  tasks:

    - name: Creating user by Ansible vault
      user:
        name: "{{ username }}"
        password: "{{ password }}"