---
- name: Web service
  hosts: targets
  become: true
  tasks:
    - name: Install http and firewall packages
      dnf:
        name:
          - httpd
          - firewalld
        state: present

    - name: Modify the web page
      copy:
        content: "I am Nazmul"
        dest: /var/www/html/index.html

    - name: Enable firewalld service
      service:
        name: firewalld
        enabled: yes
        state: restarted

    - name: Allow http ports on firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: Enable and Restart the web service
      service:
        name: httpd
        enabled: yes
        state: restarted
        