---
- name: Test web service
  hosts: localhost
  become: no
  tasks:
    - name: connect to web server
      uri:
        url: http://172.16.7.215
        return_content: yes
        status_code: 200